# permissions for end users to view mypythonapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mypythonapp-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: frontendapp
    app.kubernetes.io/part-of: frontendapp
    app.kubernetes.io/managed-by: kustomize
  name: mypythonapp-viewer-role
rules:
- apiGroups:
  - frontend.stickers.com
  resources:
  - mypythonapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - frontend.stickers.com
  resources:
  - mypythonapps/status
  verbs:
  - get
