apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: myapp-container
    image: myapp-image:latest
    ports:
    - containerPort: 5001
  - name: monitoring-container
    image: busybox:latest
    command: ['sh', '-c', 'while true; do wget -O /dev/null http://localhost:5001; sleep 10; done']
