apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp-pod
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5001
    nodePort: 30000
  type: NodePort
